from enum import StrEnum


class RoleName(StrEnum):
    ADMINISTRATOR = "ADMINISTRATOR"
    DEVELOPER = "DEVELOPER"
    OPERATOR = "OPERATOR"
    VIEWER = "VIEWER"


class SourceType(StrEnum):
    WEB_PAGE = "WEB_PAGE"
    WEB_SITE = "WEB_SITE"
    REST_API = "REST_API"
    GRAPHQL_API = "GRAPHQL_API"
    JSON_FILE = "JSON_FILE"
    XML_FILE = "XML_FILE"
    PDF_DOCUMENT = "PDF_DOCUMENT"
    DOCX_DOCUMENT = "DOCX_DOCUMENT"
    XLSX_DOCUMENT = "XLSX_DOCUMENT"
    CSV_DOCUMENT = "CSV_DOCUMENT"
    AUTHENTICATED_WEB = "AUTHENTICATED_WEB"
    MANUAL_UPLOAD = "MANUAL_UPLOAD"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"
    SUCCESS_EMPTY_ALLOWED = "SUCCESS_EMPTY_ALLOWED"
    SUCCESS_EMPTY_UNEXPECTED = "SUCCESS_EMPTY_UNEXPECTED"


TERMINAL_RUN_STATUSES = frozenset(status.value for status in RunStatus if status not in {RunStatus.QUEUED, RunStatus.RUNNING})
SUCCESSFUL_RUN_STATUSES = frozenset({
    RunStatus.SUCCESS.value,
    RunStatus.PARTIAL_SUCCESS.value,
    RunStatus.WAITING_FOR_REVIEW.value,
    RunStatus.SUCCESS_EMPTY_ALLOWED.value,
})


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CORRECTED = "CORRECTED"
