import {FormEvent,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from './api';
import {ConfirmButton,ErrorPanel,Header,Loading,Modal,Table} from './components';

type ApiToken={id:string;name:string;token_prefix:string;scopes:string[];dataset_ids:string[];rate_limit_per_minute:number;expires_at:string|null;last_used_at:string|null;revoked_at:string|null;created_at:string};
type CreatedToken=ApiToken&{token:string};

export function ApiTokensPage(){
  const queryClient=useQueryClient();const [creating,setCreating]=useState(false);const [clearToken,setClearToken]=useState<CreatedToken|null>(null);const [error,setError]=useState('');
  const tokens=useQuery({queryKey:['api-tokens'],queryFn:()=>api<ApiToken[]>('/api-tokens')});
  const datasets=useQuery({queryKey:['datasets'],queryFn:()=>api<any[]>('/datasets')});
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const form=new FormData(event.currentTarget);try{const created=await api<CreatedToken>('/api-tokens',{method:'POST',body:JSON.stringify({name:form.get('name'),dataset_ids:form.getAll('dataset_ids'),scopes:['datasets:read'],rate_limit_per_minute:Number(form.get('rate_limit_per_minute')||120),expires_at:form.get('expires_at')?new Date(String(form.get('expires_at'))).toISOString():null})});setClearToken(created);setCreating(false);await queryClient.invalidateQueries({queryKey:['api-tokens']})}catch(value){setError(value instanceof Error?value.message:String(value))}}
  async function revoke(id:string){await api(`/api-tokens/${id}`,{method:'DELETE'});await queryClient.invalidateQueries({queryKey:['api-tokens']})}
  if(tokens.isLoading||datasets.isLoading)return <Loading/>;if(tokens.error)return <ErrorPanel error={tokens.error}/>;
  return <><Header title="API-токены" subtitle="Read-only доступ внешних агентов к выбранным dataset." actions={<button onClick={()=>setCreating(true)}>Создать токен</button>}/>{error&&<div className="error">{error}</div>}<div className="panel"><Table rows={(tokens.data||[]).map(token=>({...token,dataset_ids:token.dataset_ids.join(', '),scopes:token.scopes.join(', '),state:token.revoked_at?'REVOKED':'ACTIVE'}))} columns={['name','token_prefix','dataset_ids','scopes','rate_limit_per_minute','last_used_at','state']}/>{(tokens.data||[]).filter(token=>!token.revoked_at).map(token=><ConfirmButton key={token.id} className="danger small" onConfirm={()=>revoke(token.id)}>Отозвать {token.name}</ConfirmButton>)}</div>{creating&&<Modal title="Новый machine-to-machine токен" onClose={()=>setCreating(false)}><form className="form" onSubmit={create}><label>Название<input name="name" required placeholder="AI news reader"/></label><fieldset><legend>Dataset scope</legend>{datasets.data?.map(dataset=><label className="checkbox" key={dataset.id}><input type="checkbox" name="dataset_ids" value={dataset.id}/><span>{dataset.name}</span></label>)}</fieldset><label>Запросов в минуту<input name="rate_limit_per_minute" type="number" min="1" max="10000" defaultValue="120"/></label><label>Истекает (необязательно)<input name="expires_at" type="datetime-local"/></label><button>Создать</button></form></Modal>}{clearToken&&<Modal title="Скопируйте токен сейчас" onClose={()=>setClearToken(null)}><div className="warning-list">После закрытия значение больше не показывается и нигде в браузере не сохраняется.</div><pre data-testid="clear-api-token">{clearToken.token}</pre><button onClick={()=>navigator.clipboard.writeText(clearToken.token)}>Копировать</button></Modal>}</>
}
